version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      postgres:
        condition: service_started
      migratedb:
        condition: service_completed_successfully

    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command:
      [
     
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "dev",
      ]
    ports:
      - 4000:4000
      - 3000:3000
    environment:
      - DATABASE_URI=postgresql://postgres:password@postgres:5432/Instagram?schema=public
      - SECRET_KEY="LASJKDA;LSKDA;Oshdlfsadjkafsdhflkajsdfliosdjknx"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Instagram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  migratedb:
    image: app:latest
    depends_on:
      postgres:
        condition: service_started
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npx",
        "prisma",
        "db",
        "push",
      ]
    build:
      context: .
      target: development

    environment:
      - DATABASE_URI=postgresql://postgres:password@postgres:5432/Instagram
volumes:
  postgres:
